[package]
name = "autopeer"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
common = { path = "../common" }
worker = "0.7.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
